data = struct( ...
    'W_S', W_S_des_memo(1:indice_contatore), ...
    'W_S_max', W_S_max_memo(1:indice_contatore), ...
    'WTO', WTO_memo(1:indice_contatore), ...
    'S', S_ref_memo(1:indice_contatore), ...
    'b', b_ref_memo(1:indice_contatore), ...
    'c_root', croot_memo(1:indice_contatore), ...
    'S_vert', S_vert_memo(1:indice_contatore), ...
    'S_orizz', S_orizz_memo(1:indice_contatore), ...
    'CL_crociera', CL_des_memo(1:indice_contatore), ...
    'E_crociera', E_curr_memo(1:indice_contatore), ...
    'P_curr', P_curr_memo(1:indice_contatore), ...
    'P_tot', P_tot_memo(1:indice_contatore), ...
    'P_ice', P_ice_memo(1:indice_contatore), ...
    'P_em', P_em_memo(1:indice_contatore), ...
    'phi_ice_cl', phi_ice_cl_memo(1:indice_contatore), ...
    'phi_ice_cr', phi_ice_cr_memo(1:indice_contatore), ...
    'phi_ice_de', phi_ice_de_memo(1:indice_contatore), ...
    'Hp', Hp_memo(1:indice_contatore), ...
    'E_batt_inst', E_batt_memo(1:indice_contatore), ...
    'OEW', OEW_memo(1:indice_contatore), ...
    'W_wing', W_wing_memo(1:indice_contatore), ...
    'W_fus', W_fus_memo(1:indice_contatore), ...
    'W_tail', W_tail_memo(1:indice_contatore), ...
    'W_LG', W_LG_memo(1:indice_contatore), ...
    'W_propuls', W_propuls_memo(1:indice_contatore), ...
    'W_fuelsys', W_fuelsys_memo(1:indice_contatore), ...
    'W_hydr', W_hydr_memo(1:indice_contatore), ...
    'W_elec', W_elec_memo(1:indice_contatore), ...
    'W_antiice', W_antiice_memo(1:indice_contatore), ...
    'W_instr', W_instr_memo(1:indice_contatore), ...
    'W_avionics', W_avionics_memo(1:indice_contatore), ...
    'W_engine_sys', W_engine_sys_memo(1:indice_contatore), ...
    'W_furn', W_furn_memo(1:indice_contatore), ...
    'W_services', W_services_memo(1:indice_contatore), ...
    'W_crew', W_crew_memo(1:indice_contatore), ...
    'W_battery', W_batt_memo(1:indice_contatore), ...
    'W_fuel', W_fuel_memo(1:indice_contatore), ...
    'V_fuel', W_fuel_memo(1:indice_contatore) / 0.8, ...
    'W_block_fuel', W_block_fuel_memo(1:indice_contatore), ...
    'W_payload', W_payload_memo(1:indice_contatore), ...
    'ADP', ADP_memo(1:indice_contatore) ...
    );
writetable(struct2table(data), 'dati_convergenza.csv');